# Generated by Django 4.1.1 on 2022-11-17 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'MCQ Category',
            },
        ),
        migrations.CreateModel(
            name='option_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField()),
                ('answer_list', models.CharField(max_length=300)),
                ('mcq_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_app.mcq_category')),
            ],
            options={
                'verbose_name_plural': 'MCQ Questions',
            },
        ),
        migrations.CreateModel(
            name='user_mcq_submitted_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_value', models.CharField(max_length=350)),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_app.option_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MCQ User Submitted',
            },
        ),
        migrations.CreateModel(
            name='MCQ_UserCategoryAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_app.mcq_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MCQUser Attempts Answer',
            },
        ),
    ]
